### ISSUE TITLE
Build Fail #2: ./mono/metadata/loader.h: Too many levels of symbolic links

### ISSUE THREAD

**Issue by RussellHaley** [radovanovic/monobsd#2]
gmake[4]: Entering directory '/usr/home/freebsd/git/monobsd/mono/mini'
  CC       libmini_la-mini-amd64.lo
In file included from mini-amd64.c:16:0:
mini.h:17:34: fatal error: ./mono/metadata/loader.h: Too many levels of symbolic links
 #include <'mono/metadata/loader.h>
                                  ^
compilation terminated.
gmake[4]: **\* [Makefile:2372: libmini_la-mini-amd64.lo] Error 1
gmake[4]: Leaving directory '/usr/home/freebsd/git/monobsd/mono/mini'
gmake[3]: **\* [Makefile:1227: all] Error 2
gmake[3]: Leaving directory '/usr/home/freebsd/git/monobsd/mono/mini'
gmake[2]: **\* [Makefile:445: all-recursive] Error 1
gmake[2]: Leaving directory '/usr/home/freebsd/git/monobsd/mono'
gmake[1]: **\* [Makefile:523: all-recursive] Error 1
gmake[1]: Leaving directory '/usr/home/freebsd/git/monobsd'
gmake: **\* [Makefile:453: all] Error 2

Hey, I'm not even sure what that means. I'll have a dig into it this afternoon unless you have some insight.

**Comment by radovanovic** [comment]
Have no clue, are you doing some exotic build, or just normal autogen/configure/gmake?

**Comment by RussellHaley** [comment]
I could have screwed something up. I'll do another clean and try again.

**Comment by radovanovic** [comment]
It might be that you are doing clean build without bootstrap compiler, I didn't try that now and I remember when I was trying to build mono that way some time ago it was failing with some crazy errors.

**Comment by RussellHaley** [comment]
Nope, just me mucking it up.  I ran the following:
% gmake clean
% ./autogen.sh --disable-dtrace
% gmake

mcs is compiling things now.
